blog/urls.py
from django.urls import path
from . import views as bv

urlpatterns = [
    path("", bv.index, name="index"),
    path(r"article/<int:article_id>/", bv.article_page, name="article"),
    path("edit/<int:article_id>/", bv.page_edit, name="edit_page"),
    path("edit/action/", bv.action_edit, name="edit_action"),
]

fodo/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views as fv

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", fv.index),
    path("blog/", include(("blog.urls", "blog"), namespace="blog")),
    path("polls/", include("polls.urls")),
]

polls/urls.py
from django.urls import path

from . import views

app_name = "polls"
urlpatterns = [
    path("", views.IndexView.as_view(), name="index"),
    path("<int:pk>/", views.DetailView.as_view(), name="detail"),
    path("<int:pk>/results", views.ResultsView.as_view(), name="results"),
    path("<int:question_id>/vote", views.vote, name="vote"),
]

blog/models.py
from django.db import models

# Create your models here.


class Article(models.Model):
    title = models.CharField(max_length=32, default="title")
    content = models.TextField(null=True)
    pub_time = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title


class Person(models.Model):
    first_name = models.CharField(max_length=30)
    last_name = models.CharField(max_length=30)

    def __str__(self):
        return self.first_name + self.last_name


class Musician(models.Model):
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=30)
    instrument = models.CharField(max_length=100)


class Album(models.Model):
    artist = models.ForeignKey(Musician, on_delete=models.CASCADE)
    name = models.CharField(max_length=100)
    release_date = models.DateField
    star_nums = models.IntegerField

polls/models.py
from django.db import models

from django.utils import timezone
import datetime


# Create your models here.


class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField("date published")

    def __str__(self):
        return self.question_text

    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <= now


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

blog/views.py
from django.shortcuts import render

# Create your views here.

from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse

from blog.models import Article


# 主页
def index(request):
    articles = Article.objects.all()
    return render(request, "blog/index.html", {"articles": articles})


# 文章页
def article_page(request, article_id):
    article = Article.objects.get(pk=article_id)
    return render(request, "blog/article.html", {"article": article})


# 文章编辑页
def page_edit(request, article_id):
    if str(article_id) == "0":
        return render(request, "blog/edit.html")

    article = Article.objects.get(pk=article_id)
    return render(request, "blog/edit.html", {"article": article})


# 文章发表方法
def action_edit(request):
    title = request.POST.get("title", "title")
    content = request.POST.get("content", "content")
    article_id = request.POST.get("article_id", "0")
    # 发表新文章
    if article_id == "0":
        Article.objects.create(title=title, content=content)
        articles = Article.objects.all()
        return render(request, "blog/index.html", {"articles": articles})
    # 修改文章并返回文章页
    article = Article.objects.get(pk=article_id)
    article.title = title
    article.content = content
    article.save()
    # return render(request, 'blog/article.html', {'article': article})
    return HttpResponseRedirect(reverse("blog:article", args=(article.id,)))

fodo/views.py
from django.shortcuts import render


def index(request):
    return render(request, "index.html", {"index": "Django Projects"})

polls/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from django.utils import timezone
from django.views import generic

from .models import Question, Choice


# Create your views here.


class IndexView(generic.ListView):
    template_name = "polls/index.html"
    context_object_name = "latest_question_list"

    def get_queryset(self):
        return Question.objects.filter(pub_date__lte=timezone.now()).order_by(
            "-pub_date"
        )[:5]


# def index(request):
#     latest_question_list = Question.objects.order_by('-pub_date')[:5]
#     content = {'latest_question_list': latest_question_list}
#     return render(request, 'polls/index.html', content)
"'通用视图DetailView'"


class DetailView(generic.DetailView):
    model = Question
    template_name = "polls/detail.html"


# def detail(request, question_id):
#     question = get_object_or_404(Question, pk=question_id)
#
#     return render(request, 'polls/detail.html', {'question': question})


class ResultsView(generic.DetailView):
    model = Question
    template_name = "polls/results.html"


# def results(request, question_id):
#     question = get_object_or_404(Question, pk=question_id)
#     return render(request, 'polls/results.html', {'question': question})


def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST["choice"])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form.
        return render(
            request,
            "polls/detail.html",
            {"question": question, "error_message": "You didn't select a choice.",},
        )
    else:
        selected_choice.votes += 1
        selected_choice.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse("polls:results", args=(question.id,)))

blog/templates/blog/article.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{article.title}}</title>
    <link rel="stylesheet" href="http://cdn.bootcss.com/bootstrap/3.3.0/css/bootstrap.min.css">
</head>
<body>
<div class="container">
    <div class="col-md-9 col-sm-10">
        <h2>{{article.title}}</h2>
        <p>
            {{article.content}}
        </p>
        <br>
        <br>
        <p>
        <a class="btn btn-primary" href="{% url 'blog:edit_page' article.id %}">修改文章</a>
            <a class="btn btn-light" href="/blog">返回Blog首页</a>
        </p>
    </div>
</div>

</body>
</html>

blog/templates/blog/edit.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Edit Page</title>
    <link rel="stylesheet" href="http://cdn.bootcss.com/bootstrap/3.3.0/css/bootstrap.min.css">

</head>
<body>
<div class="container">
    <div class="row">
        <div class="col-md-9">
            <div class="panel">
                <div class="panel-heading">
                    <h2>修改文章</h2>
                </div>
                <div class="panel-body">
                    <form class="form-horizontal" action="{% url 'blog:edit_action' %}" method="post">
                        {% csrf_token %}

                        <input type="hidden" name="article_id" value="{{ article.id | default:'0' }}">
                        <div class="form-group">
                            <label class="col-sm-2 label-control">文章标题</label>
                                  <div class="col-sm-6">
                                      <input class="form-control" type="text" name="title" value="{{article.title}}">
                                  </div>
                        </div>
                        <div class="form-group">
                            <label class="col-sm-2 label-control">文章内容</label>
                            <div class="col-sm-6">
                                <input class="form-control" type="text" name="content" value="{{article.content}}">
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-sm-4 col-sm-offset-2">
                                <input role="button" class="btn btn-primary" type="submit" value="发表">
                            </div>
                        </div>
                    </form>
                </div>
            </div>

        </div>
    </div>
</div>

</body>
</html>

blog/templates/blog/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Blog </title>
    <link rel="stylesheet" href="http://cdn.bootcss.com/bootstrap/3.3.0/css/bootstrap.min.css">
</head>
<body>
<div class="container">
    <div class="col-md-9">
        <h2>文章列表：</h2>
    <p>
        <a class="btn btn-primary" href="{% url 'blog:edit_page' 0 %}">写文章</a>
        <a class="btn btn-light" href="/">返回首页</a>
    </p>
    {% for article in articles %}
    <p>
         <a href="{% url 'blog:article' article.id %}">{{article.title}}</a>
    </p>

    {% endfor %}
    </div>

</div>
</body>
</html>

fodo/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>首页</title>
    <link rel="stylesheet" type="text/css" href="https://cdn.bootcss.com/bootstrap/3.3.0/css/bootstrap.css">
</head>
<body>
<div class="container">
    <div class="row">
        <div class="col-md-9">
            <h1>{{ index }}</h1>

            <div>
                <p>
                    <a class="btn btn-lg" href="/blog">Blog</a>
                </p>
                <p>
                    <a class="btn btn-lg" href="/polls">Polls</a>
                </p>
            </div>

        </div>
    </div>
</div>

</body>
</html>

polls/templates/polls/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>问题详情页</title>
    <link rel="stylesheet" href="http://cdn.bootcss.com/bootstrap/3.3.0/css/bootstrap.min.css">

</head>
<body>
<div class="container">
    <div class="row">
        <div class="col-md-6">

            <h1>{{ question.question_text }}</h1>

            {% if error_message %}
            <p><strong>{{ error_message }}</strong></p>
            {% endif %}

            <form class="form-group" action="{% url 'polls:vote' question.id %}" method="post">
                {% csrf_token %}
                {% for choice in question.choice_set.all %}
                <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{choice.id}}">
                <label for="choice{{forloop.counter}}">{{ choice.choice_text }} </label>
                <br>
                {% endfor %}
                <input class="btn btn-primary" type="submit" value="Vote">
            </form>

            <p>
                <a href="/polls/">返回Polls首页</a>
            </p>
        </div>
    </div>
</div>

</body>
</html>

polls/templates/polls/index.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>投票 | Polls</title>
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}">
    <link rel="stylesheet" href="http://cdn.bootcss.com/bootstrap/3.3.0/css/bootstrap.min.css">
</head>

<body style="padding-top:50px">
    <div class="container">
        <div class="row">
            <div class="col-md-6">
                <h1>Polls list</h1>
                {% if latest_question_list %}
                <ul class="list-group" style="font-size:16px">
                    {% for question in latest_question_list %}
                    <li class="list-group-item">
                        <a href="{% url 'polls:detail' question.id %}">{{question.question_text}}</a>
                    </li>
                    {% endfor %}
                </ul>
                {% else %}
                <p>No polls are available.</p>
                {% endif %}

                <p><a class="btn btn-light" href="/">返回首页</a></p>
            </div>
        </div>
    </div>
</body>

</html>

polls/templates/polls/results.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>投票结果页</title>
    <link rel="stylesheet" href="http://cdn.bootcss.com/bootstrap/3.3.0/css/bootstrap.min.css">

</head>

<body>
    <div class="container">
        <div class="row">
            <div class="col-md-6">
                <h1>{{ question.question_text }}</h1>

                <ul class="list-group">
                    {% for choice in question.choice_set.all %}
                    <li class="list-group_item">{{ choice.choice_text }} -- {{ choice.votes }}
                        vote{{ choice.votes|pluralize }}</li>
                    {% endfor %}
                </ul>

                <a class="btn btn-primary" href="{% url 'polls:detail' question.id %}">Vote again?</a>

                <p class="btn">
                    <a href="/polls">返回Polls首页</a>
                </p>
            </div>
        </div>
    </div>

</body>

</html>